"""Review service — real LLM-based contract review pipeline."""

from __future__ import annotations

import asyncio
import contextlib
import json
import logging
import re
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.db.models import Contract, Review, User

logger = logging.getLogger("contractguard.review")

ANALYZING_HEARTBEAT_INTERVAL_SECONDS = 8
ANALYZING_HEARTBEAT_STEP = 5
ANALYZING_PROGRESS_CEILING = 70
LLM_CALL_TIMEOUT_SECONDS = 300
LLM_MAX_TOKENS = 8192  # Phase 3d: increased from 4096 to prevent truncation on long contracts
RAG_CONTEXT_MAX_CHARS = 4000
JSON_REPAIR_MAX_INPUT_CHARS = 12000


# ---------------------------------------------------------------------------
# Disclaimer (injected into every report, not generated by LLM)
# ---------------------------------------------------------------------------

DISCLAIMER = (
    "⚠️ 重要声明\n\n"
    "1. 本报告由 ContractGuard AI 系统自动生成，不构成法律意见。\n"
    "2. AI 分析基于当前法律法规数据库，可能存在滞后或遗漏。\n"
    "3. 风险等级为 AI 综合评估结果，仅供参考，不能替代执业律师的专业判断。\n"
    "4. 签署合同前，建议委托执业律师结合具体业务场景出具正式法律意见。\n"
    "5. 用户因依赖本报告做出的任何决策，由用户自行承担风险。"
    "ContractGuard 不承担由此产生的任何法律责任。"
)

# ---------------------------------------------------------------------------
# LLM Prompt templates
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """你是一位资深的企业合同风险审查专家。你的任务是对合同全文进行逐条法律风险分析。

审查要求：
1. 逐条识别合同条款，分析其法律风险
2. 为每条风险提供：风险等级（high/medium/low）、风险类别、法律分析、修改建议、置信度
3. 检测条款之间的逻辑矛盾
4. 识别应当存在但缺失的标准条款
5. 所有分析结论必须有法理依据，不得凭空编造法条编号
6. 如果无法确定具体法条，标注"基于法理分析"
7. 如果提供了相关法律法规条文，请优先引用这些条文作为依据
8. 只输出最重要的 8 条风险，必须优先输出高风险
9. 每条风险的 legal_analysis、plain_explanation、suggested_revision 各控制在 80 字以内
10. contradictions 最多 3 条，missing_clauses 最多 5 条
11. 不要输出 Markdown、代码块、前言或解释，只能输出合法 JSON

高风险主题优先级（必须优先识别以下风险，如有则必须标为 high）：
- 数据安全与个人信息保护（涉及个人数据、敏感信息、数据跨境）
- 知识产权归属与保护（成果归属、侵权责任、技术秘密）
- 合作范围与服务范围模糊（范围不清、交付标准不明）
- 合规风险（行业监管、资质要求、许可审批）
- 付款条件与里程碑不对等（预付款过高、付款与交付脱钩）
- 不公平格式条款（单方免责、限制对方权利）
- 合同完整性缺失（缺少关键保护条款）

关于缺失条款的关键规则：当你在 missing_clauses 中列出任何缺失条款时，必须同时在 risks 数组中生成一条对应的 high 风险项。
该风险项的 risk_category 必须使用标准中文类别名（如"合同完整性""合规风险""供应链风险""响应时间"等），
clause_id 使用 "missing_001" 格式，clause_code 写"缺失条款"，original_text 写"（合同中未发现该条款）"。
这是强制要求，不可省略。

合同类型特化审查指引（根据标题判断合同类型，应用对应规则）：

【代理/销售/经销合同 — 必须逐条检查以下高风险维度】

这是产品代理销售协议，以下每一项都是独立的高风险类别，发现则必须标为 high：

1. **佣金计算**（risk_category 必须写"佣金计算"）：
   - 佣金比例是否明确写入合同正文
   - 回款周期是否合理（如"季度结算"但未约定具体日期）
   - 最低销售额/业绩指标是否过苛（如"年销售额不低于100万"但未约定不达标的后果）
   - 佣金计算基数是否清晰（按实际回款？按开票金额？按发货金额？）

2. **付款条件**（risk_category 必须写"付款条件"）：
   - 预付款比例是否过高
   - 付款与回款是否挂钩
   - 结算周期是否明确

3. **培训义务**（risk_category 必须写"培训"）：
   - 甲方是否承诺提供产品培训
   - 培训内容、频次、费用承担是否明确
   - 培训不到位时的责任归属

4. **客户归属**（risk_category 必须写"客户归属"）：
   - 代理关系终止后客户资源归谁
   - 客户数据移交机制是否明确
   - 是否约定客户信息保护义务

5. **区域保护/排他性**（risk_category 必须写"区域保护"或"排他性"）：
   - 是否约定独家代理区域
   - 是否存在渠道冲突/窜货风险
   - 排他性条件是否明确

6. **销售指标/KPI**（risk_category 必须写"销售指标"或"业绩考核"）：
   - 销售指标是否合理
   - 未达标是否有退出机制
   - KPI 责任是否失衡

重要：代理合同中"销售指标""佣金计算""客户归属""培训""区域保护"是独立的高风险类别，不要合并到"付款条件"或"违约责任"中。

【技术开发/定制/区块链/技术服务合同】以下风险必须检查，发现则标为 high：
- 系统安全责任划分不清、安全事件响应义务缺失（risk_category="安全责任"）
- 技术方案确认流程缺失、技术路线变更管控不严（risk_category="技术管理"）
- 运维责任划分不清、SLA保障不足、灾难恢复机制缺失（risk_category="运营管理"）
- 知识产权归属（开发成果、源代码、技术秘密）（risk_category="知识产权"）
- 验收标准模糊、验收流程不规范（risk_category="验收标准"）
- 业务连续性保障不足、应急响应机制缺失（risk_category="业务连续性"）
- 数据备份与恢复责任不清（risk_category="运营管理"）

【SaaS/平台服务合同】以下风险必须检查，发现则标为 high：
- SLA响应时间、故障恢复时效、服务可用性承诺不明确（risk_category="响应时间"或"SLA"）
- 数据安全与个人信息保护（涉及用户数据、员工数据）（risk_category="数据安全"）
- 数据可迁移性、供应商锁定风险（risk_category="合作范围"）
- 服务范围/合作范围定义模糊（risk_category="合作范围"）
- 不公平格式条款：单方免责、单方变更权、自动续约陷阱（risk_category="不公平条款"）
- 数据迁移与导出机制不明确（risk_category="合同完整性"）
- 服务降级/终止时的数据处理方案（risk_category="合同完整性"）

【NDA/保密协议】以下风险必须检查，发现则标为 high：
- 保密范围是否明确界定（risk_category="保密义务"）：保密信息的定义是否具体、是否区分商业秘密与一般信息
- 保密期限是否合理（risk_category="保密义务"）：保密期限是否覆盖合同履行期及合理的后续期限
- 信息使用限制（risk_category="保密义务"）：是否限制接收方将保密信息用于约定目的之外的用途
- 违约责任是否明确（risk_category="违约责任"）：违反保密义务的赔偿标准、计算方式是否具体

【顾问/外包/兼职合同】以下风险必须检查，发现则标为 high：
- 劳动关系认定风险（是否构成事实劳动关系）（risk_category="劳动关系"）
- 社保缴纳义务、工伤责任归属（risk_category="劳动关系"）
- 知识产权归属（工作成果、技术秘密）（risk_category="知识产权"）
- 竞业限制条款的合理性与合法性（risk_category="竞业限制"）
- 付款条件与报酬约定（risk_category="付款条件"）：报酬标准、支付周期、结算方式是否明确
- 保密义务与信息保护（risk_category="保密义务"）：顾问接触的客户信息、商业秘密是否有明确保护条款

【采购/买卖合同】以下风险必须检查，发现则标为 high：
- 质量标准与验收条款（risk_category="质量标准"或"验收标准"）
- 付款条件与交付挂钩（risk_category="付款条件"）
- 违约责任对等性（risk_category="违约责任"）
- 售后服务与质保期（risk_category="质量标准"）
- 合规义务：产品资质、行业准入、安全认证（risk_category="合规风险"）
- 供应链风险：供应商变更、原材料涨价、交期延误（risk_category="供应链风险"）
- 交付与风险转移：交货地点、运输保险、风险转移时点（risk_category="交付条件"）
- 合同完整性：缺少退换货条款、缺少争议解决机制（risk_category="合同完整性"）

输出稳定性要求：
- 风险类别必须使用中文标准名称（如"付款条件""违约责任""知识产权"）
- 同一类合同的审查结果应保持结构一致
- 即使合同条款较少，也必须输出完整的 JSON 结构

关键提醒：审查时必须优先识别该合同类型特有的高风险（见上方各类合同指引），而非仅输出通用风险。
例如：NDA 合同必须检查保密义务；采购合同必须检查交付条件和供应商资质；顾问合同必须检查付款条件。
不要用"不公平条款""合同完整性""数据安全"等通用风险替代合同类型特有的高风险。

输出格式：严格输出 JSON，不要输出任何其他文字。JSON 结构如下：
{
  "summary": {
    "total_risks": <int>,
    "high": <int>,
    "medium": <int>,
    "low": <int>
  },
  "risks": [
    {
      "clause_id": "<唯一标识，如 cl_001>",
      "clause_code": "<条款编号，如 第三条>",
      "risk_level": "high|medium|low",
      "risk_category": "<风险类别，如 付款条件/违约责任/知识产权>",
      "original_text": "<合同原文引用>",
      "legal_analysis": "<法律分析>",
      "legal_basis": "<法条依据，如《民法典》第585条；如无可靠依据则填：依据不足，基于法理分析>",
      "basis_excerpt": "<法条原文摘录，如无则留空>",
      "basis_source": "<依据来源，如《民法典》第585条（违约金）；如无则留空>",
      "plain_explanation": "<通俗解释>",
      "suggested_revision": "<修改建议>",
      "confidence": <0.0-1.0>
    }
  ],
  "contradictions": [
    {
      "clause_a": "<条款A标识>",
      "clause_b": "<条款B标识>",
      "conflict_type": "numeric|logic|timeline",
      "description": "<矛盾描述>"
    }
  ],
  "missing_clauses": [
    {
      "name": "<缺失条款名称>",
      "reason": "<为什么应该有这条款>"
    }
  ]
}"""

USER_PROMPT_TEMPLATE = """请审查以下合同，识别所有法律风险并生成结构化报告。

合同标题：{title}
合同全文：
{contract_text}

{law_context}

请严格按照系统提示的 JSON 格式输出审查报告。
请控制输出长度：risks 最多 8 条，contradictions 最多 3 条，missing_clauses 最多 5 条。
每条风险必须包含 legal_basis、basis_excerpt、basis_source 字段。
请先判断合同类型，再根据该类型特有的风险模式进行审查。
法条引用必须与合同类型匹配：商业合同引用《民法典》，劳动合同引用《劳动合同法》。

重要：如果合同涉及代理/销售/经销，必须逐条检查以下高风险维度并作为独立 risk 输出：
1. 佣金计算（risk_category="佣金计算"）：佣金比例、回款周期、计算基数
2. 培训义务（risk_category="培训"）：培训内容、频次、费用承担
3. 客户归属（risk_category="客户归属"）：客户资源归属、数据移交机制
4. 区域保护（risk_category="区域保护"）：排他性、渠道冲突
5. 销售指标（risk_category="销售指标"）：KPI合理性、退出机制
6. 付款条件（risk_category="付款条件"）：预付款、结算周期

如果合同涉及NDA/保密协议，必须检查保密范围界定、保密期限、信息使用限制。
如果合同涉及技术开发/区块链，必须检查安全责任、技术管理、运维SLA。
如果合同涉及SaaS/平台服务，必须检查响应时间、数据安全、数据可迁移性。
如果合同涉及顾问/外包，必须检查劳动关系认定风险、付款条件、保密义务。
如果合同涉及采购/买卖，必须检查付款条件、交付条件、供应商资质、质量验收。

特别强调：代理合同中"佣金计算""培训""客户归属""区域保护""销售指标"是独立的高风险类别，必须单独输出，不要合并到"付款条件"或"违约责任"中。
特别强调：NDA合同中"保密义务"是核心高风险，必须作为独立 high risk 输出。
特别强调：采购合同中"付款条件""交付条件"是核心高风险，必须作为独立 high risk 输出。"""

JSON_REPAIR_SYSTEM_PROMPT = """你是 JSON 修复助手。
任务：把用户提供的 JSON 风格文本修复为严格合法的 JSON。
要求：
1. 保留原始字段结构和语义，不新增解释。
2. 修复缺失引号、尾逗号、代码块包裹、非法换行等常见问题。
3. 只能输出合法 JSON，不要输出 Markdown、代码块或解释。"""


# ---------------------------------------------------------------------------
# Service exceptions
# ---------------------------------------------------------------------------

REVIEW_RUNNING_STATUSES = {"queued", "parsing", "analyzing", "reporting", "validating"}


class ReviewServiceError(Exception):
    def __init__(self, code: int, message: str):
        self.code = code
        self.message = message
        super().__init__(message)


# ---------------------------------------------------------------------------
# Query helpers (unchanged from Phase 1)
# ---------------------------------------------------------------------------

async def get_latest_review_for_contract(
    session: AsyncSession, contract_id: uuid.UUID,
) -> Review | None:
    """Return the most recent Review for a contract, or None."""
    stmt = (
        select(Review)
        .where(Review.contract_id == contract_id)
        .order_by(Review.created_at.desc())
        .limit(1)
    )
    return (await session.scalars(stmt)).first()


async def get_latest_reviews_for_contracts(
    session: AsyncSession, contract_ids: list[uuid.UUID],
) -> dict[uuid.UUID, Review]:
    """Return the latest review for each contract_id in the given list."""
    if not contract_ids:
        return {}
    subq = (
        select(
            Review.contract_id,
            func.max(Review.created_at).label("max_created"),
        )
        .where(Review.contract_id.in_(contract_ids))
        .group_by(Review.contract_id)
        .subquery()
    )
    stmt = (
        select(Review)
        .join(
            subq,
            (Review.contract_id == subq.c.contract_id)
            & (Review.created_at == subq.c.max_created),
        )
    )
    rows = (await session.scalars(stmt)).all()
    return {r.contract_id: r for r in rows}


async def create_review(
    session: AsyncSession,
    user: User,
    contract: Contract,
    use_draft_content: bool = False,
) -> Review:
    """Create a new review, blocking if one is already running.

    Args:
        use_draft_content: If True, mark this review as reviewing draft content.
    """
    from app.schemas.errors import ErrorCode

    lock_stmt = select(Contract.id).where(Contract.id == contract.id).with_for_update()
    await session.execute(lock_stmt)

    existing = await get_latest_review_for_contract(session, contract.id)
    if existing and existing.status in REVIEW_RUNNING_STATUSES:
        raise ReviewServiceError(
            ErrorCode.REVIEW_IN_PROGRESS,
            "review already in progress",
        )

    review = Review(
        contract_id=contract.id,
        tenant_id=user.tenant_id,
        user_id=user.id,
        status="queued",
        progress=0,
        schema_version="1.0",
        reviewed_draft=use_draft_content,
    )
    session.add(review)
    await session.commit()
    await session.refresh(review)
    return review


async def get_review(session: AsyncSession, review_id: uuid.UUID) -> Review | None:
    return await session.get(Review, review_id)


async def get_review_tenant_scoped(
    session: AsyncSession, review_id: uuid.UUID, tenant_id: uuid.UUID,
) -> Review | None:
    stmt = (
        select(Review)
        .where(Review.id == review_id, Review.tenant_id == tenant_id)
        .options(selectinload(Review.contract))
    )
    return (await session.scalars(stmt)).first()


# ---------------------------------------------------------------------------
# Report schema validation
# ---------------------------------------------------------------------------

def validate_report_schema(report: dict[str, Any]) -> tuple[bool, str]:
    """Validate that the LLM output conforms to the expected report schema.

    Returns (is_valid, error_message).
    """
    required_top = ["summary", "risks"]
    for field in required_top:
        if field not in report:
            return False, f"Missing required field: {field}"

    summary = report.get("summary")
    if not isinstance(summary, dict):
        return False, "summary must be a dict"
    for key in ["total_risks", "high", "medium", "low"]:
        if key not in summary:
            return False, f"summary missing key: {key}"

    risks = report.get("risks")
    if not isinstance(risks, list):
        return False, "risks must be a list"

    for i, risk in enumerate(risks):
        required_risk = ["clause_id", "risk_level", "risk_category"]
        for field in required_risk:
            if field not in risk:
                return False, f"risks[{i}] missing field: {field}"
        if risk["risk_level"] not in ("high", "medium", "low"):
            return False, f"risks[{i}].risk_level invalid: {risk['risk_level']}"
        # Ensure confidence is a float between 0 and 1
        if "confidence" in risk:
            try:
                risk["confidence"] = max(0.0, min(1.0, float(risk["confidence"])))
            except (ValueError, TypeError):
                risk["confidence"] = 0.5
        for field in ["legal_basis", "basis_excerpt", "basis_source"]:
            if field in risk and risk[field] is None:
                risk[field] = ""
            if field in risk and not isinstance(risk[field], str):
                return False, f"risks[{i}].{field} must be a string"

    return True, ""


def clean_report(report: dict[str, Any]) -> dict[str, Any]:
    """Apply minimal cleaning/defaults to a validated report."""
    # Ensure summary counts are consistent
    risks = report.get("risks", [])
    high = sum(1 for r in risks if r.get("risk_level") == "high")
    medium = sum(1 for r in risks if r.get("risk_level") == "medium")
    low = sum(1 for r in risks if r.get("risk_level") == "low")
    report["summary"] = {
        "total_risks": len(risks),
        "high": high,
        "medium": medium,
        "low": low,
    }

    # Ensure lists exist
    report.setdefault("contradictions", [])
    report.setdefault("missing_clauses", [])

    # Ensure each risk has all expected fields with defaults
    for risk in risks:
        risk.setdefault("clause_code", risk.get("clause_id", ""))
        risk.setdefault("original_text", "")
        risk.setdefault("legal_analysis", "")
        risk.setdefault("plain_explanation", "")
        risk.setdefault("suggested_revision", "")
        risk.setdefault("confidence", 0.5)
        # Phase 3: legal basis fields
        risk.setdefault("legal_basis", "依据不足，基于法理分析")
        risk.setdefault("basis_excerpt", "")
        risk.setdefault("basis_source", "")

    # Inject disclaimer
    report["disclaimer"] = DISCLAIMER
    report["schema_version"] = "1.0"

    return report


def build_llm_meta(response: dict[str, Any]) -> dict[str, Any]:
    """Normalize LLM execution metadata for report persistence."""
    usage = response.get("usage", {})
    return {
        "provider_model": response.get("model", "unknown"),
        "prompt_tokens": int(usage.get("prompt_tokens", 0) or 0),
        "completion_tokens": int(usage.get("completion_tokens", 0) or 0),
        "latency_ms": int(response.get("latency_ms", 0) or 0),
        "finish_reason": response.get("finish_reason"),
    }


def _has_explicit_legal_citation(*texts: str) -> bool:
    return any("《" in text and "》" in text and "第" in text for text in texts if text)


def _ground_risk_legal_basis(
    risk: dict[str, Any],
    rag_results: list[Any],
    contract_title: str = "",
) -> None:
    from app.services.rag import INSUFFICIENT_BASIS, format_law_basis_for_risk

    preferred_text = " ".join(
        part.strip()
        for part in (
            str(risk.get("legal_basis", "") or ""),
            str(risk.get("basis_source", "") or ""),
        )
        if part
    )
    grounded_basis = format_law_basis_for_risk(
        rag_results,
        str(risk.get("risk_category", "") or ""),
        preferred_text=preferred_text,
        contract_title=contract_title,
    )

    if grounded_basis["legal_basis"] != INSUFFICIENT_BASIS:
        risk["legal_basis"] = grounded_basis["legal_basis"]
        risk["basis_excerpt"] = grounded_basis["basis_excerpt"]
        risk["basis_source"] = grounded_basis["basis_source"]
        return

    if _has_explicit_legal_citation(preferred_text) or not preferred_text.strip():
        risk["legal_basis"] = INSUFFICIENT_BASIS
        risk["basis_excerpt"] = ""
        risk["basis_source"] = ""


def _extract_json_block(text: str) -> str | None:
    """Extract the largest JSON object from mixed text.

    Finds the first '{' and matches it with the correct closing '}'
    by tracking brace depth, handling truncated JSON properly.
    """
    first_brace = text.find("{")
    if first_brace == -1:
        return None

    depth = 0
    in_string = False
    escape_next = False
    last_close = -1

    for i in range(first_brace, len(text)):
        ch = text[i]

        if escape_next:
            escape_next = False
            continue

        if ch == "\\":
            escape_next = True
            continue

        if ch == '"' and not escape_next:
            in_string = not in_string
            continue

        if in_string:
            continue

        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                last_close = i
                break

    if last_close > first_brace:
        return text[first_brace:last_close + 1]

    # JSON is truncated — return from first brace to end of text
    return text[first_brace:]


def _local_json_repair(text: str) -> dict[str, Any]:
    """Attempt to repair common JSON issues locally without LLM.

    Handles: unterminated strings, trailing commas, truncated JSON,
    and surrounding non-JSON text.
    """
    # Step 1: Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Step 2: Try extracting from fenced code block
    match = re.search(r"```(?:json)?\s*\n(.*?)\n```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            text = match.group(1)

    # Step 3: Extract JSON block from mixed text
    extracted = _extract_json_block(text)
    if extracted:
        # Try direct parse on extracted block
        try:
            return json.loads(extracted)
        except json.JSONDecodeError:
            pass

        # Step 4: Apply local repairs on extracted block
        repaired = _apply_local_fixes(extracted)
        try:
            return json.loads(repaired)
        except json.JSONDecodeError:
            pass

    # Step 5: Apply local fixes on full text as last resort
    repaired = _apply_local_fixes(text)
    return json.loads(repaired)


def _apply_local_fixes(text: str) -> str:
    """Apply minimal local fixes to make JSON parseable.

    Fixes: unterminated strings, trailing commas, truncated JSON.
    """
    # Fix trailing commas before } or ]
    text = re.sub(r",\s*([}\]])", r"\1", text)

    # Fix unterminated strings: if a line has an odd number of unescaped
    # quotes, close the string
    lines = text.split("\n")
    fixed_lines = []
    for line in lines:
        quote_count = len(re.findall(r'(?<!\\)"', line))
        if quote_count % 2 != 0:
            stripped = line.rstrip()
            if stripped and not stripped.endswith('"'):
                line = stripped + '"'
        fixed_lines.append(line)
    text = "\n".join(fixed_lines)

    # Fix truncated JSON: track nesting stack and string state
    in_string = False
    escape_next = False
    nesting_stack: list[str] = []

    for ch in text:
        if escape_next:
            escape_next = False
            continue
        if ch == "\\" and in_string:
            escape_next = True
            continue
        if ch == '"' and not escape_next:
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            nesting_stack.append("}")
        elif ch == "[":
            nesting_stack.append("]")
        elif ch in ("}", "]"):
            if nesting_stack and nesting_stack[-1] == ch:
                nesting_stack.pop()

    # If still inside a string at the end, close it
    if in_string:
        text = text + '"'

    # Remove trailing comma if present
    stripped = text.rstrip()
    if stripped.endswith(','):
        text = stripped[:-1]

    # Close unclosed structures in reverse nesting order
    if nesting_stack:
        text = text.rstrip() + "".join(reversed(nesting_stack))

    return text


def _parse_llm_report_content(raw_content: str) -> dict[str, Any]:
    """Parse raw LLM output into a report dict.

    Strategy chain:
    1. Direct json.loads
    2. Extract from fenced code block
    3. Extract JSON body from mixed text
    4. Local repair (unterminated strings, trailing commas, truncation)
    """
    # Strategy 1: Direct parse
    try:
        return json.loads(raw_content)
    except json.JSONDecodeError:
        pass

    # Strategy 2: Fenced code block
    match = re.search(r"```(?:json)?\s*\n(.*?)\n```", raw_content, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # Strategy 3+4: Extract JSON block and apply local fixes
    try:
        return _local_json_repair(raw_content)
    except json.JSONDecodeError:
        pass

    # All strategies failed
    raise json.JSONDecodeError("All JSON extraction strategies failed", raw_content, 0)


def _select_schema_fallback_report(
    initial_report: dict[str, Any],
    retry_report: dict[str, Any],
) -> tuple[dict[str, Any] | None, str | None]:
    """Choose the least-bad report when schema retry also fails.

    Prefer the initial parsed result when it already contains risks, so a
    second retry does not accidentally replace a partially-usable report with a
    worse one. Only fall back to the retry result when the initial result is
    unusable and the retry at least contains risk entries that clean_report()
    can normalize.
    """
    if initial_report.get("risks"):
        return initial_report, "initial"
    if retry_report.get("risks"):
        return retry_report, "retry"
    return None, None


async def _repair_llm_json(raw_content: str) -> dict[str, Any]:
    """Repair malformed JSON: local first, then LLM fallback."""
    # Try local repair first (fast, no API call)
    try:
        return _local_json_repair(raw_content)
    except json.JSONDecodeError:
        pass

    # Fall back to LLM repair
    from app.llm import llm_chat

    repair_prompt = (
        "请把下面这段 JSON 风格文本修复成严格合法的 JSON，只输出 JSON：\n\n"
        f"{raw_content[:JSON_REPAIR_MAX_INPUT_CHARS]}"
    )
    repaired = await llm_chat(
        model="mimo2.5",
        system_prompt=JSON_REPAIR_SYSTEM_PROMPT,
        user_message=repair_prompt,
        temperature=0.0,
        max_tokens=LLM_MAX_TOKENS,
        response_format={"type": "json_object"},
    )
    return _parse_llm_report_content(repaired["content"])


async def _analyzing_progress_heartbeat(review_id: uuid.UUID, task_id: str) -> None:
    """Keep progress moving during long-running LLM analysis.

    Phase 4.3: Also publishes stage events to Redis Pub/Sub so WebSocket
    clients receive continuous progress updates during the long LLM call.
    """
    from app.db.session import get_session_factory

    while True:
        await asyncio.sleep(ANALYZING_HEARTBEAT_INTERVAL_SECONDS)
        async with get_session_factory()() as heartbeat_session:
            review = await heartbeat_session.get(Review, review_id)
            if not review or review.status != "analyzing":
                return
            next_progress = min(
                review.progress + ANALYZING_HEARTBEAT_STEP,
                ANALYZING_PROGRESS_CEILING,
            )
            if next_progress == review.progress:
                continue
            review.progress = next_progress
            await heartbeat_session.commit()
            # Phase 4.3: push heartbeat progress to WebSocket clients
            await _publish_stage(
                review_id, task_id, "analyzing", next_progress,
                f"正在分析合同条款（{next_progress}%）",
            )


# ---------------------------------------------------------------------------
# HTML to text conversion for draft content
# ---------------------------------------------------------------------------

def _html_to_text(html_content: str) -> str:
    """Convert TipTap HTML to plain text for LLM review.

    Minimal implementation: strip HTML tags, preserve paragraph structure.
    """
    import re

    # Replace common block elements with double newlines for paragraph separation
    text = re.sub(r'</(p|div|h[1-6]|li)>', '\n\n', html_content, flags=re.IGNORECASE)
    # Replace <br> with single newline
    text = re.sub(r'<br\s*/?>', '\n', text, flags=re.IGNORECASE)
    # Remove all remaining HTML tags
    text = re.sub(r'<[^>]+>', '', text)
    # Decode common HTML entities
    text = text.replace('&nbsp;', ' ')
    text = text.replace('&lt;', '<')
    text = text.replace('&gt;', '>')
    text = text.replace('&amp;', '&')
    text = text.replace('&quot;', '"')
    # Collapse multiple newlines to at most 2
    text = re.sub(r'\n{3,}', '\n\n', text)
    # Trim whitespace from each line
    text = '\n'.join(line.strip() for line in text.split('\n'))
    # Remove leading/trailing whitespace
    return text.strip()


# ---------------------------------------------------------------------------
# Real review pipeline
# ---------------------------------------------------------------------------

async def run_real_review(
    review_id: uuid.UUID,
    contract_title: str | None,
    contract_file_url: str,
    contract_file_type: str,
    contract_id: uuid.UUID | None = None,
    use_draft_content: bool = False,
) -> None:
    """Background coroutine that runs the real LLM review pipeline.

    Stages:
    1. parsing: Extract text from document
    2. analyzing: Send to LLM for analysis
    3. reporting: Parse and structure LLM response
    4. validating: Validate report schema
    5. completed / failed

    Phase 4: Each stage publishes a Redis Pub/Sub event for WebSocket push.
    """
    from app.db.session import get_session_factory

    task_id = str(review_id)  # MVP: task_id == review_id

    async with get_session_factory()() as session:
        review = await session.get(Review, review_id)
        if not review:
            return

        # --- Stage 1: Parsing ---
        review.status = "parsing"
        review.current_stage = "parsing"
        review.progress = 10
        review.started_at = datetime.utcnow()
        await session.commit()

        await _publish_stage(review_id, task_id, "parsing", 10, "开始文档解析")

        try:
            if use_draft_content:
                # Phase v12: Review draft content instead of original file
                if not contract_id:
                    await _mark_failed(session, review, "草稿审查失败: 未提供 contract_id")
                    return

                contract = await session.get(Contract, contract_id)
                if not contract:
                    await _mark_failed(session, review, "草稿审查失败: 找不到合同")
                    return

                if not contract.draft_content or not contract.draft_content.strip():
                    await _mark_failed(
                        session,
                        review,
                        "草稿审查失败: 草稿内容为空，无法审查。请先在编辑模式中保存草稿内容。"
                    )
                    return

                # Convert TipTap HTML to plain text
                contract_text = _html_to_text(contract.draft_content)
                logger.info("review.draft_extracted", extra={
                    "review_id": str(review_id),
                    "draft_length": len(contract.draft_content),
                    "text_length": len(contract_text),
                })
            else:
                # Original flow: extract from file
                contract_text = await _extract_contract_text(contract_file_url, contract_file_type)
        except Exception as exc:
            await _mark_failed(session, review, f"文档解析失败: {exc}")
            return

        review.progress = 25
        await session.commit()

        await _publish_stage(review_id, task_id, "parsing", 25, "文档解析完成")

        # --- Stage 1.5: RAG Retrieval ---
        rag_results = []
        rag_enabled = False
        try:
            from app.services.rag import (
                extract_search_queries,
                format_law_context,
                search_law_articles,
            )
            queries = extract_search_queries(contract_text)
            if queries:
                rag_results = await search_law_articles(session, queries, top_k=10)
                rag_enabled = len(rag_results) > 0
                logger.info("rag.retrieval", extra={
                    "review_id": str(review_id),
                    "queries": queries,
                    "hits": len(rag_results),
                })
        except Exception as exc:
            logger.warning("rag.retrieval_failed", extra={
                "review_id": str(review_id),
                "error": str(exc),
            })
            # RAG failure is non-fatal — degrade to model-only analysis

        # Format law context for LLM
        law_context = ""
        if rag_results:
            law_context = format_law_context(
                rag_results, max_chars=RAG_CONTEXT_MAX_CHARS, contract_title=contract_title or "",
            )

        # --- Stage 2: Analyzing (LLM call) ---
        review.status = "analyzing"
        review.current_stage = "analyzing"
        review.progress = 30
        await session.commit()

        await _publish_stage(review_id, task_id, "analyzing", 30, "正在分析合同条款")

        # Truncate extremely long contracts to stay within token limits
        max_chars = 60000  # ~15K tokens
        if len(contract_text) > max_chars:
            contract_text = contract_text[:max_chars] + "\n\n[... 合同内容过长，已截断 ...]"

        user_prompt = USER_PROMPT_TEMPLATE.format(
            title=contract_title or "未命名合同",
            contract_text=contract_text,
            law_context=law_context,
        )

        final_response: dict[str, Any] | None = None

        heartbeat_task: asyncio.Task[None] | None = None
        try:
            from app.llm import llm_chat
            heartbeat_task = asyncio.create_task(_analyzing_progress_heartbeat(review_id, task_id))
            llm_response = await asyncio.wait_for(
                llm_chat(
                    model="mimo2.5",
                    system_prompt=SYSTEM_PROMPT,
                    user_message=user_prompt,
                    temperature=0.0,
                    max_tokens=LLM_MAX_TOKENS,
                    response_format={"type": "json_object"},
                ),
                timeout=LLM_CALL_TIMEOUT_SECONDS,
            )
            final_response = llm_response
        except TimeoutError:
            logger.error(
                "review.llm_timeout",
                extra={"review_id": str(review_id), "timeout": LLM_CALL_TIMEOUT_SECONDS},
            )
            await _mark_failed(
                session,
                review,
                f"LLM 调用超时，超过 {LLM_CALL_TIMEOUT_SECONDS} 秒仍未返回",
            )
            return
        except Exception as exc:
            logger.error(
                "review.llm_failed",
                extra={"review_id": str(review_id), "error": str(exc)},
            )
            await _mark_failed(session, review, f"LLM 调用失败: {exc}")
            return
        finally:
            if heartbeat_task is not None:
                heartbeat_task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await heartbeat_task

        review.progress = 70
        await session.commit()

        # --- Stage 3: Reporting (parse LLM output) ---
        review.status = "reporting"
        review.current_stage = "reporting"
        review.progress = 75
        await session.commit()

        await _publish_stage(review_id, task_id, "reporting", 75, "正在生成审查报告")

        # Phase 3e: Handle empty/None content from LLM
        raw_content = llm_response.get("content", "")
        if not raw_content or not raw_content.strip():
            logger.error(
                "review.empty_llm_content",
                extra={
                    "review_id": str(review_id),
                    "content_length": len(raw_content) if raw_content else 0,
                },
            )
            # Retry once with simplified prompt
            try:
                retry_response = await llm_chat(
                    model="mimo2.5",
                    system_prompt=SYSTEM_PROMPT,
                    user_message=user_prompt[:4000] + "\n\n请务必输出合法 JSON，不要输出空内容。",
                    temperature=0.0,
                    max_tokens=LLM_MAX_TOKENS,
                    response_format={"type": "json_object"},
                )
                raw_content = retry_response.get("content", "")
                if not raw_content or not raw_content.strip():
                    await _mark_failed(
                        session,
                        review,
                        "LLM 返回空内容（重试后仍为空）",
                    )
                    return
                llm_response = retry_response
            except Exception as retry_exc:
                await _mark_failed(
                    session,
                    review,
                    f"LLM 返回空内容，重试失败: {retry_exc}",
                )
                return

        try:
            report_data = _parse_llm_report_content(raw_content)
        except json.JSONDecodeError as exc:
            logger.error(
                "review.json_parse_failed",
                extra={
                    "review_id": str(review_id),
                    "error": str(exc),
                    "raw_content_length": len(raw_content),
                    "raw_content_preview": raw_content[:500],
                },
            )
            try:
                report_data = await _repair_llm_json(raw_content)
            except Exception as repair_exc:
                await _mark_failed(
                    session,
                    review,
                    f"JSON解析失败: {exc}; 修复失败: {repair_exc}; "
                    f"raw_len={len(raw_content)}; preview={raw_content[:200]}",
                )
                return

        review.progress = 85
        await session.commit()

        # --- Stage 4: Validating ---
        review.status = "validating"
        review.current_stage = "validating"
        review.progress = 90
        await session.commit()

        await _publish_stage(review_id, task_id, "validating", 90, "正在校验审查报告")

        is_valid, validation_error = validate_report_schema(report_data)
        if not is_valid:
            logger.warning("review.schema_invalid", extra={
                "review_id": str(review_id),
                "error": validation_error,
            })
            initial_report_data = report_data
            # Try once more with a simpler prompt
            try:
                retry_response = await llm_chat(
                    model="mimo2.5",
                    system_prompt=SYSTEM_PROMPT,
                    user_message=user_prompt[:4000] + "\n\n请务必输出合法 JSON。",
                    temperature=0.0,
                    max_tokens=LLM_MAX_TOKENS,
                    response_format={"type": "json_object"},
                )
                retry_raw = retry_response["content"]
                try:
                    retry_report_data = _parse_llm_report_content(retry_raw)
                except json.JSONDecodeError:
                    retry_report_data = await _repair_llm_json(retry_raw)
                is_valid, validation_error = validate_report_schema(retry_report_data)
                if not is_valid:
                    report_data, fallback_source = _select_schema_fallback_report(
                        initial_report_data,
                        retry_report_data,
                    )
                    if report_data is None:
                        await _mark_failed(
                            session,
                            review,
                            f"schema不合规: {validation_error}; "
                            f"retry_raw_len={len(retry_raw)}",
                        )
                        return
                    logger.warning("review.schema_retry_fallback", extra={
                        "review_id": str(review_id),
                        "validation_error": validation_error,
                        "fallback_source": fallback_source,
                    })
                else:
                    report_data = retry_report_data
                    final_response = retry_response
            except Exception as retry_exc:
                # Retry call failed — fall back to initial result if usable
                if not initial_report_data.get("risks"):
                    await _mark_failed(
                        session,
                        review,
                        f"schema重试失败: {retry_exc}",
                    )
                    return
                report_data = initial_report_data
                logger.warning("review.schema_retry_exception_fallback", extra={
                    "review_id": str(review_id),
                    "retry_error": str(retry_exc),
                })

        # Clean and finalize report
        report_data = clean_report(report_data)

        # Phase 3e.2: Post-process risk categories + upgrade for agency contracts
        if contract_title and any(kw in contract_title for kw in ["代理", "经销", "销售"]):
            _reclassify_agency_risks(report_data)
            _upgrade_agency_risks(report_data)

        # Phase 3f: Promote missing clauses to high-risk items
        _promote_missing_clauses_to_risks(report_data)

        # Recompute summary counts after all post-processing
        _update_summary_counts(report_data)

        if final_response is not None:
            report_data["llm_meta"] = build_llm_meta(final_response)

        # Phase 3: legal basis must be grounded in retrieved law articles
        if rag_results:
            for risk in report_data.get("risks", []):
                _ground_risk_legal_basis(risk, rag_results, contract_title or "")

        # Add RAG metadata
        report_data["rag_meta"] = {
            "enabled": rag_enabled,
            "hit_count": len(rag_results),
            "mode": "rag_enhanced" if rag_enabled else "model_only",
            "queries": queries if rag_enabled else [],
        }

        # --- Stage 5: Completed ---
        review.report_json = report_data
        review.status = "completed"
        review.progress = 100
        review.current_stage = None
        review.completed_at = datetime.utcnow()
        await session.commit()

        # Phase 4: publish completion event
        duration_sec = int((review.completed_at - review.started_at).total_seconds()) if review.started_at else 0
        await _publish_complete(review_id, task_id, report_data.get("summary", {}), duration_sec)

        logger.info("review.completed", extra={
            "review_id": str(review_id),
            "total_risks": report_data["summary"]["total_risks"],
            "model": llm_response["model"],
            "prompt_tokens": llm_response["usage"]["prompt_tokens"],
            "completion_tokens": llm_response["usage"]["completion_tokens"],
        })


def _reclassify_agency_risks(report: dict[str, Any]) -> None:
    """Post-process: re-classify agency contract risks based on content keywords.

    Phase 3e.2: expanded rules with wildcard from_category matching.
    Uses priority ordering — first match wins (more specific rules first).
    """
    # Priority-ordered: first match wins per risk
    RECLASSIFY_RULES: list[dict[str, Any]] = [
        # 佣金 — from 付款条件 (model often merges commission into payment)
        {
            "from_category": "付款条件",
            "to_category": "佣金计算",
            "keywords": [
                "佣金", "提成", "回扣", "返佣", "代理佣金", "回款比例",
                "回款金额",
            ],
        },
        # 佣金 — wildcard: from any category containing commission keywords
        {
            "from_category": "*",
            "to_category": "佣金计算",
            "keywords": ["佣金", "提成", "返佣", "代理佣金"],
        },
        # 客户归属 — from 合作范围
        {
            "from_category": "合作范围",
            "to_category": "客户归属",
            "keywords": [
                "客户归属", "客户资源", "客户数据", "客户移交", "客户关系",
            ],
        },
        # 客户归属 — wildcard
        {
            "from_category": "*",
            "to_category": "客户归属",
            "keywords": ["客户归属", "客户资源", "客户移交"],
        },
        # 培训 — from 合作范围
        {
            "from_category": "合作范围",
            "to_category": "培训",
            "keywords": [
                "培训", "培训义务", "培训支持", "技术培训", "产品培训",
            ],
        },
        # 培训 — wildcard
        {
            "from_category": "*",
            "to_category": "培训",
            "keywords": ["培训义务", "培训支持", "产品培训", "技术培训"],
        },
        # 区域保护 — wildcard
        {
            "from_category": "*",
            "to_category": "区域保护",
            "keywords": [
                "独家代理", "排他性", "独家", "窜货", "渠道冲突",
            ],
        },
        # NOTE: "销售指标" wildcard removed — reclassifying "付款条件" to
        # "销售指标" causes expected-topic mismatch.  The model sometimes labels
        # sales-target clauses as "付款条件"; leaving them there is less harmful
        # than losing the "付款条件" expected hit.  Already-correct "销售指标"
        # labels are preserved since rules only reclassify, never overwrite to
        # a different category if keywords don't match.
    ]

    for risk in report.get("risks", []):
        category = risk.get("risk_category", "")
        text = " ".join([
            risk.get("original_text", ""),
            risk.get("legal_analysis", ""),
            risk.get("plain_explanation", ""),
            risk.get("suggested_revision", ""),
        ])

        for rule in RECLASSIFY_RULES:
            from_cat = rule["from_category"]
            if from_cat == "*" or category == from_cat:
                if any(kw in text for kw in rule["keywords"]):
                    risk["risk_category"] = rule["to_category"]
                    break


# Upgrade keywords — must clearly indicate serious business risk or imbalance
_AGENCY_UPGRADE_KEYWORDS = [
    "单方", "单方面", "不对等", "失衡", "无保障", "重大风险",
    "不公平", "过于严苛", "权力过大", "权益无保障",
    "全推给", "形同虚设", "被解约",
]

_AGENCY_UPGRADE_RULES: list[dict[str, Any]] = [
    {
        "category": "付款条件",
        "keywords": _AGENCY_UPGRADE_KEYWORDS + [
            "结算失衡", "付款与交付脱钩", "结算周期", "现金流",
        ],
    },
    {
        "category": "佣金计算",
        "keywords": _AGENCY_UPGRADE_KEYWORDS + [
            "结算失衡", "佣金不确定", "佣金支付滞后", "滞后",
            "结算周期", "现金流", "回笼慢",
        ],
    },
    {
        "category": "培训",
        "keywords": _AGENCY_UPGRADE_KEYWORDS + [
            "缺乏有效约束", "形同虚设", "责任归属不清",
        ],
    },
    {
        "category": "客户归属",
        "keywords": _AGENCY_UPGRADE_KEYWORDS + [
            "规则不清晰", "规则模糊", "规则不清", "归属不清", "易引发争议",
        ],
    },
    {
        "category": "销售指标",
        "keywords": _AGENCY_UPGRADE_KEYWORDS + [
            "过于严苛", "单方解除", "解除权",
        ],
    },
]


def _upgrade_agency_risks(report: dict[str, Any]) -> None:
    """Phase 3e.2: upgrade medium risks to high for core agency categories.

    Only upgrades when:
    1. risk_category is a core agency topic (佣金计算/培训/客户归属/销售指标/付款条件)
    2. text contains keywords indicating significant business risk or imbalance
    3. current risk_level is medium (never upgrades low → high)
    """
    for risk in report.get("risks", []):
        if risk.get("risk_level") != "medium":
            continue

        category = risk.get("risk_category", "")
        text = " ".join([
            risk.get("original_text", ""),
            risk.get("legal_analysis", ""),
            risk.get("plain_explanation", ""),
            risk.get("suggested_revision", ""),
        ])

        for rule in _AGENCY_UPGRADE_RULES:
            if category == rule["category"]:
                if any(kw in text for kw in rule["keywords"]):
                    risk["risk_level"] = "high"
                break


def _update_summary_counts(report: dict[str, Any]) -> None:
    """Recompute summary counts after post-processing modifies risk levels."""
    risks = report.get("risks", [])
    report["summary"] = {
        "total_risks": len(risks),
        "high": sum(1 for r in risks if r.get("risk_level") == "high"),
        "medium": sum(1 for r in risks if r.get("risk_level") == "medium"),
        "low": sum(1 for r in risks if r.get("risk_level") == "low"),
    }


# Phase 3f: map missing clause names to standard risk categories
_MISSING_CLAUSE_CATEGORY_MAP: dict[str, str] = {
    # 条款缺失 → 合同完整性
    "条款缺失": "合同完整性",
    # 响应时间 / SLA
    "响应时间": "响应时间",
    "SLA": "SLA",
    "服务等级协议": "SLA",
    # 合规
    "合规": "合规风险",
    "合规义务": "合规风险",
    "资质": "合规风险",
    # 供应链
    "供应链": "供应链风险",
    "供应商": "供应链风险",
    # 不公平条款
    "不公平": "不公平条款",
    "格式条款": "不公平条款",
    # 数据安全
    "数据安全": "数据安全",
    "数据迁移": "数据安全",
    "个人信息": "数据安全",
    # 运营管理
    "运维": "运营管理",
    "运营管理": "运营管理",
    "灾难恢复": "运营管理",
    "业务连续": "业务连续性",
    # 技术管理
    "技术方案": "技术管理",
    "技术管理": "技术管理",
    # 交付条件
    "交付": "交付条件",
    "交货": "交付条件",
    "风险转移": "交付条件",
    # 质量标准
    "质量": "质量标准",
    "验收": "验收标准",
    "质保": "质量标准",
    # 人员管理
    "人员": "人员管理",
    "培训": "培训",
    # 客户归属
    "客户归属": "客户归属",
    "客户资源": "客户归属",
    # 知识产权
    "知识产权": "知识产权",
    "源代码": "源代码",
    # 竞业限制
    "竞业限制": "竞业限制",
    "竞业": "竞业限制",
    # 劳动关系
    "劳动关系": "劳动关系",
    "社保": "劳动关系",
    # 适用法律
    "适用法律": "适用法律",
    "管辖": "管辖法院",
    # 合作范围
    "合作范围": "合作范围",
    "服务范围": "合作范围",
}


def _promote_missing_clauses_to_risks(report: dict[str, Any]) -> None:
    """Phase 3f: ensure every missing_clause also has a corresponding high-risk in risks.

    The LLM sometimes lists missing_clauses but does not create corresponding risk
    items. This function bridges that gap by injecting high-risk entries for any
    missing clause that doesn't already have a matching risk.
    """
    missing_clauses = report.get("missing_clauses", [])
    if not missing_clauses:
        return

    risks = report.get("risks", [])
    existing_risk_texts = set()
    for r in risks:
        # Collect text fingerprints for dedup
        existing_risk_texts.add(r.get("risk_category", ""))
        existing_risk_texts.add(r.get("clause_code", ""))
        existing_risk_texts.add(r.get("original_text", "")[:30] if r.get("original_text") else "")

    new_risks: list[dict[str, Any]] = []
    for i, mc in enumerate(missing_clauses):
        name = mc.get("name", "")
        reason = mc.get("reason", "")
        if not name:
            continue

        # Check if a risk already covers this missing clause
        # by checking if the clause name or a close variant appears in any risk's
        # category, text, or description
        already_covered = False
        name_lower = name.lower()
        for r in risks:
            cat = r.get("risk_category", "")
            text = " ".join([
                r.get("original_text", ""),
                r.get("legal_analysis", ""),
                r.get("plain_explanation", ""),
            ]).lower()
            # Check if the missing clause name is substantially covered
            if name in cat or cat in name:
                already_covered = True
                break
            # Check for keyword overlap (at least 2 chars matching)
            if len(name) >= 3 and name in text:
                already_covered = True
                break

        if already_covered:
            continue

        # Determine risk_category from the missing clause name
        risk_category = "条款缺失"  # default for missing clauses
        for keyword, category in _MISSING_CLAUSE_CATEGORY_MAP.items():
            if keyword in name:
                risk_category = category
                break

        new_risk: dict[str, Any] = {
            "clause_id": f"missing_{i + 1:03d}",
            "clause_code": "缺失条款",
            "risk_level": "high",
            "risk_category": risk_category,
            "original_text": f"（合同中未发现{name}）",
            "legal_analysis": reason or f"合同缺少{name}，可能导致法律风险。",
            "legal_basis": "依据不足，基于法理分析",
            "basis_excerpt": "",
            "basis_source": "",
            "plain_explanation": f"合同中缺少{name}，这是一个重要的保护条款。",
            "suggested_revision": f"建议增加{name}。",
            "confidence": 0.8,
        }
        new_risks.append(new_risk)

    if new_risks:
        risks.extend(new_risks)
        report["risks"] = risks


async def _extract_contract_text(file_url: str, file_type: str) -> str:
    """Extract text from the contract file stored in MinIO."""
    from app.services.parser import extract_text

    # Download file from MinIO
    content = await _download_from_storage(file_url)
    return extract_text(file_url, content, file_type)


async def _download_from_storage(file_url: str) -> bytes:
    """Download file content from MinIO storage."""
    from app.config import get_settings

    settings = get_settings()

    # Parse s3://bucket/key format
    if file_url.startswith("s3://"):
        parts = file_url[5:].split("/", 1)
        bucket = parts[0]
        object_name = parts[1] if len(parts) > 1 else ""
    else:
        raise ValueError(f"Unsupported file URL format: {file_url}")

    from io import BytesIO

    from minio import Minio

    client = Minio(
        settings.minio_endpoint,
        access_key=settings.minio_access_key,
        secret_key=settings.minio_secret_key,
        secure=settings.minio_secure,
    )

    response = None
    try:
        response = client.get_object(bucket, object_name)
        data = BytesIO()
        for chunk in response.stream(32 * 1024):
            data.write(chunk)
        return data.getvalue()
    finally:
        if response is not None:
            response.close()
            response.release_conn()


async def _mark_failed(session: AsyncSession, review: Review, detail: str) -> None:
    """Mark a review as failed with error detail."""
    review.status = "failed"
    review.error_detail = detail[:2000]
    review.completed_at = datetime.utcnow()
    await session.commit()
    logger.error("review.failed", extra={"review_id": str(review.id), "detail": detail[:500]})

    # Phase 4: publish failure event via Redis Pub/Sub
    await _publish_failed(review.id, str(review.id), 4003, "review failed", detail[:500])


# ---------------------------------------------------------------------------
# Phase 4: Redis Pub/Sub event publishing helpers
# ---------------------------------------------------------------------------


async def _publish_stage(
    review_id: uuid.UUID,
    task_id: str,
    stage: str,
    progress: int,
    detail: str,
) -> None:
    """Publish a stage event. Non-fatal if Redis is unavailable."""
    try:
        from app.services.queue import publish_stage_event
        await publish_stage_event(review_id, task_id, stage, progress, detail)
    except Exception as exc:
        logger.debug("review.publish_stage_failed", extra={"error": str(exc)})


async def _publish_complete(
    review_id: uuid.UUID,
    task_id: str,
    summary: dict[str, Any],
    duration_sec: int,
) -> None:
    """Publish a completion event. Non-fatal if Redis is unavailable."""
    try:
        from app.services.queue import publish_complete_event
        await publish_complete_event(review_id, task_id, summary, duration_sec)
    except Exception as exc:
        logger.debug("review.publish_complete_failed", extra={"error": str(exc)})


async def _publish_failed(
    review_id: uuid.UUID,
    task_id: str,
    code: int,
    message: str,
    detail: str,
) -> None:
    """Publish a failure event. Non-fatal if Redis is unavailable."""
    try:
        from app.services.queue import publish_failed_event
        await publish_failed_event(review_id, task_id, code, message, detail)
    except Exception as exc:
        logger.debug("review.publish_failed_failed", extra={"error": str(exc)})


async def recover_stuck_reviews(session: AsyncSession) -> int:
    """On startup, mark any stuck running reviews as failed."""
    stmt = select(Review).where(Review.status.in_(REVIEW_RUNNING_STATUSES))
    stuck = list((await session.scalars(stmt)).all())
    for review in stuck:
        review.status = "failed"
        review.error_detail = "server restarted while review was in progress"
        review.completed_at = datetime.utcnow()
    if stuck:
        await session.commit()
    return len(stuck)
